### ISSUE TITLE
abapGit starting folder

### ISSUE THREAD

**Issue by larshp** [Microsoft/ABAP-SDK-for-Azure#1]
Hi,
Cool to see another abapGit based project ✨ 

A tip:
If you like, you can set the starting folder under "Advanced" -> "Repo settings" the starting folder can be changed to eg "/src/" that way all the ABAP artifacts will end up in that folder.
And everything in "/ABAP SDK for Azure" will automatically be ignored

**Comment by NaveenKurmadas** [comment]
Thanks for Tip. We will incorporate the Changes.

**Comment by NaveenKurmadas** [comment]
when i tried to change the starting folder to /src/. I'm getting error 'unexpected folder structure'.  Is there something I missed?

**Comment by christianguenter2** [comment]
Besides moving the folders zadf, zrest and zssf_con to /src you have to move package.devc.xml also. Then it works for me.

https://github.com/christianguenter2/ABAP-SDK-for-Azure/tree/move_to_src
![image](https://user-images.githubusercontent.com/17437789/40702130-e9643274-63e0-11e8-98d4-da53ace32b91.png)

**Comment by larshp** [comment]
@christianguenter2 did you also get the error? This looks like a bug in abapGit, it should ignore the root package.devc.xml if it is outside of the starting folder

**Comment by christianguenter2** [comment]
Sorry forgot to mention.
I did all changes (move the folders and files to /src/ and change .abapgit.xml) with my local git client, pushed it to github and pulled it into abapGit. You can't do the whole operation directly in abapGit afaik.

**Comment by christianguenter2** [comment]
@larshp got the error when package.devc.xml wasn't in the root folder.

**Comment by larshp** [comment]
looks like this has been done, cool

will keep https://github.com/larshp/abapGit/issues/1425 for further investigation
