### ISSUE TITLE
SAS Token Support

### ISSUE THREAD

**Issue by mvoros** [microsoft/ABAP-SDK-for-Azure#101]
Hi,

this is a new feature request. I used SDK to integrate with the third party and they provided already generated SAS token instead of SAS key for a blob storage container. I had no control over this and hence I had to extend the method GET_SAS_TOKEN to ignore the current logic and simply return values of SAS key as we maintained SAS token in the field SAS key. 

It would be great if this could be supported by SDK. E.g. extending config table with flag if SAS key contains the key or token and then adjusting method GET_SAS_TOKEN.

Thanks

**Comment by vikasbansal2022** [comment]
Hello @mvoros - Thanks for reaching out We upgraded the SDK master version and now BLOB class ZCL_ADF_SERVICE_BLOB. Support SAS token/SAS Key/AAD and MI as well. Please let us know if you need further input.

Regards,
Vikas

**Comment by mvoros** [comment]
Hi,

I pulled the latest version to test this change but there is a syntax error. The table ztvarvc does not exist in my system. I can see it's used couple of times but it does not seem to be defined in the repo.

**Comment by larshp** [comment]
I recommend enabling rule https://rules.abaplint.org/check_syntax/, it will help check the consistency of the files on git,

![image](https://user-images.githubusercontent.com/5888506/201043839-6f461ba5-9eea-49d7-96e9-3637cb6c8f3e.png)

**Comment by vikasbansal2022** [comment]
Thanks @larshp for recommendation. We have updated the abaplint file with check_syntax = true.

@mvoros  Please try importing again and let us know if you still face any problems.

Regards,
Vikas

**Comment by larshp** [comment]
1. also see https://github.com/microsoft/ABAP-SDK-for-Azure/issues/8

**Comment by vikasbansal2022** [comment]
Thanks @larshp @mvoros for highlighting Namespace.  Since these are being used in our landscape as well which is already in production.  we will think through about it in Point #8 

For Point @mvoros 

SAS Token can be stored same way in table ZADF_CONFIG as you are doing for SAS Key. 
we added new method ZCL_ADF_SERVICE_BLOB~DECODE_ADF_SAS_KEY to repo this will return the decoded key 
which you can call before sending data to BLOB to decode the sas key, but you have to pass this via header. Please check and let me know if you have any issue.

**Comment by mvoros** [comment]
Hi @vikasbansal2022 

I have it working, that was not the problem. I just find it not so nice to misuse header parameter to inject SAS. IMO it would be better to extend the config table with a switch (key or token) and then caller does not have to do anything specific. Internally API uses key to sign request or just appends SAS token.

**Comment by vikasbansal2022** [comment]
Thanks @mvoros for feedback,
I agree to that. we aligned SAS Key design with AAD/MI. So, you don't need to pass hardcoded key via calling program. you can retrieve it via method DECODE_ADF_SAS_KEY.
