### ISSUE TITLE
BatchEvent to EventHub

### ISSUE THREAD

**Issue by vinothsrinivasan** [microsoft/ABAP-SDK-for-Azure#102]
Hi Team, 

Is there any option to implement the batch event API using this SDK based on the below blog.

https://docs.microsoft.com/en-us/rest/api/eventhub/send-batch-events

tried to compose the payload and set the content type as per the link but still not working from ABAP, but I can achieve this in postman

**Comment by Sanjukum19** [comment]
Hi @vinothsrinivasan, 

Please let me know if you are referring to sending multiple messages in a single http request. If so, could you please refer to demo program 'ZADF_DEMO_AZURE_EVENTHUB' as this program will send multiple messages grouped into a single message to Event Hub via single HTTP request. Please let me know if I am missing any point here.

Thanks,
Sanju
