### ISSUE TITLE
Ignore pdf files

### ISSUE THREAD

**Issue by christianguenter2** [Microsoft/ABAP-SDK-for-Azure#11]
The pdf files are constantly shown as diff because they aren't pulled in abapGit.
![image](https://user-images.githubusercontent.com/17437789/40908127-1fd7056c-67e6-11e8-9d0a-f98365f41953.png)

I'd suggest to add them in the ignore section of .abapgit.xml

**Comment by NaveenKurmadas** [comment]
PDF's have been ignored now. Thanks for the feedback.
