### ISSUE TITLE
Error updating where-used list for CLAS ZCX_ADF_SERVICE_GRAPH

### ISSUE THREAD

**Issue by MartinPankraz** [microsoft/ABAP-SDK-for-Azure#119]
After a fresh setup of ABAPGit and the ABAP SDK activation failed with error message "Error updating where-used list for CLAS ZCX_ADF_SERVICE_GRAPH". Tested with S4 2021.

**Comment by larshp** [comment]
try triggering the syntax check from abapGit, does any of the classes contain syntax errors?

**Comment by MartinPankraz** [comment]
Syntax Check shows 10+ errors of types:

- The final class "ZCX_ADF_SERVICE" cannot have any subclasses.
- The REPORT/PROGRAM statement is missing, or the program type is INCLUDE.

**Comment by larshp** [comment]
yea...

suggest enabling https://rules.abaplint.org/superclass_final/

![image](https://user-images.githubusercontent.com/5888506/210237281-98aab6e4-520d-4ee0-8893-5eab7ec912f3.png)

**Comment by Sanjukum19** [comment]
Hi @MartinPankraz,

We have moved latest changes pertaining to Microsoft graph. Could you please try overwriting graph via pull and let us know if you are still encountering this error i.e. 'Error updating where-used list for CLAS ZCX_ADF_SERVICE_GRAPH'.

Best Regards,
Sanju

**Comment by MartinPankraz** [comment]
Thanks for that @Sanjukum19! Looks better now. Failed on my end with different message:

_Generation ZREST_SCREEN terminated (see long text). Return code ZREST_SCREEN

Message no. EC801

Diagnosis

Termination when generating a status because there was no more storage space.

This means that either the parameters ZTTA/CUA_AREA and ZTTA/SHORT_AREA are not compatible or the user interface of the program is too big._

**Comment by Sanjukum19** [comment]
Hi @MartinPankraz,

Could you please verify the parameters' value in RZ11 transaction i.e., if ZTTA/SHORT_AREA is at 6 times higher as that of ZTTA/CUA_AREA. Here is the SAP note for the same: [https://me.sap.com/notes/0002491252]
Please let us know if the issue still exists.

Best Regards,
Sanju

**Comment by MartinPankraz** [comment]
Even raising to maximum for short_area doesn't change the activation bottleneck. Workaround is manual second wave of activation.

**Comment by MartinPankraz** [comment]
Will test with a CAL instance for another project the next 2 weeks. If the problem doesn't occur there we can close here.

**Comment by Sanjukum19** [comment]
Hi @MartinPankraz,

Thank you! Please let us know once you complete testing on S4 Hana appliance in CAL. 
I too tried on ABAP on Hana appliance in CAL and did not encounter the above error 'ZREST_SCREEN terminated' while pulling. However, we could not confirm as the free credit got fully exhausted within a day before full testing could be completed.

Best Regards,
Sanju
