### ISSUE TITLE
Cosmos fix from PR #93 overridden

### ISSUE THREAD

**Issue by MartinPankraz** [microsoft/ABAP-SDK-for-Azure#120]
Prior fix for CosmosDB SAS token integration proposed in [PR #93 ](https://github.com/microsoft/ABAP-SDK-for-Azure/pull/93) overriden by latest [commit](https://github.com/microsoft/ABAP-SDK-for-Azure/commit/bc0d85bce8a0cd5ed1c0250d7e050365af4b7148). Consider incorporating again @vikasbansal2022?

**Comment by vikasbansal2022** [comment]
Thanks @MartinPankraz for highlighting. 

I check PR #93. The version and date format changes has been restored. Please let us know if we can close this issue.

Regards,
Vikas

**Comment by MartinPankraz** [comment]
re-testing as soon as my system is back online. Currently upgrading to 2022.

**Comment by MartinPankraz** [comment]
re-tested successfully. Thanks for the quick fix!
