### ISSUE TITLE
[FEATURE] Alternative deployment option for the SDK without 3rd party dependency

### ISSUE THREAD

**Issue by MartinPankraz** [microsoft/ABAP-SDK-for-Azure#126]
Dear community,

conversations at DSAG annual congress 2022 showed that some customers struggle installing the ABAP SDK because they are not allowed to add any 3rd party addons like ABAPGit to their landscape. I was wondering if we could provide an additional option for those. 

@larshp what do you suggest to customers that voice this challenge?

The customers in question ended up coding the integration themselves but taking inspiration from the code here at least.

KR
Martin

**Comment by larshp** [comment]
hmm, so customers what to install a 3rd party addon(ABAP-SDK-for-Azure), but they cannot do this because they are not allowed to add any 3rd party addon(abapGit)?

sounds like a chicken and egg problem

**Comment by MartinPankraz** [comment]
if you put it that way yes :-D seems like there is a tipping-point of how much Z-Code and the way it is shipped is tolerated before such concerns come up. Thanks for your comment

**Comment by larshp** [comment]
if a company doesnt use 3rd party stuff, okay. That means something like Bash, Vi, Linux, Kubernetes, Docker, git, React, TypeScript, and most programming languages are off limits, the company will IMHO have trouble competing against other companies on both software and people.

Security is another topic, there are some notes at https://docs.abapgit.org/#security, note that the abapGit source code should never reach the production system, and doesnt(typically) allow developers to do something they were not able to before.

abapGit is used actively in multiple organizations, https://docs.abapgit.org/other-where-used.html

abapGit is recommended to use by SAP when moving code from on-prem to (Embedded) Steampunk

**Comment by MartinPankraz** [comment]
Very insightfull. Will use that narrative to challenge these type of questions going forward and close this feature request as it is compelling to stay with the delivery method!
