### ISSUE TITLE
Interface GRAPH not maintained in factory method

### ISSUE THREAD

**Issue by colbyhemond** [microsoft/ABAP-SDK-for-Azure#127]
When running the `ZADF_DEMO_AZURE_GRAPH` program after configuring it, the error message "Interface Type not Maintained for Interface ADB2CGR_GE" occurs.

https://github.com/microsoft/ABAP-SDK-for-Azure/blob/adad8f956c98ebd218aae0eb4e37af6e90644e20/src/zadf/zcl_adf_service_factory.clas.abap#L100

Is there a reason the GRAPH instantiation is not implemented in `zcl_adf_service_factory=>create( )`?

**Comment by Sanjukum19** [comment]
Hi @colbyhemond,

We have moved the instantiation object for the same. Kindly check now and let us know if you are still facing issues. 

Thanks,
Sanju

**Comment by colbyhemond** [comment]
@Sanjukum19 that did the trick! Thanks!
