### ISSUE TITLE
Error reading attributes for RFC destination

### ISSUE THREAD

**Issue by christianguenter2** [Microsoft/ABAP-SDK-for-Azure#13]
I followed the instuctions of the Imlementation Guid for Azure Event hub. When I run the demo report zadf_demo_azure_eventhub or run my own tests I get this error: Error in reading attributes of RFC destnation for DEMO_EHUB.

![image](https://user-images.githubusercontent.com/17437789/41045188-2484ced2-69a8-11e8-9c81-a2fd6a358c7a.png)

If I debug it the destination is empty in ZCL_ADF_SERVICE method GET_TARGET_HOST.
![image](https://user-images.githubusercontent.com/17437789/41045421-ac66099c-69a8-11e8-9d29-d6fb294f0b63.png)

The parameter is supplied here. As far as I can see gv_rfc_destination isn't set anywhere.
![image](https://user-images.githubusercontent.com/17437789/41045492-d0b4e7a0-69a8-11e8-9b89-617e5d799633.png)

How is that intended to work? Am I missing the obvious?
If I fill gv_rfc_destination with the RFC destination in the debugger it's works.

**Comment by NaveenKurmadas** [comment]
Thanks for Identifying the issue. One of our latest changes were not completely committed to Github.  We have not fixed it. Please test now. Thanks,

**Comment by christianguenter2** [comment]
It works. Additionally I'd suggest to change the text id here to zcx_adf_service=>rfc_destination_not_maintained.
https://github.com/Microsoft/ABAP-SDK-for-Azure/blob/d2aa02e2ad490f8b8ccd0a7a2073c367beae79a1/src/zadf/zcl_adf_service.clas.abap#L569
