### ISSUE TITLE
Http version unsupport error when transfer excel from sap to azure blob

### ISSUE THREAD

**Issue by sky5685610** [microsoft/ABAP-SDK-for-Azure#136]

**Comment by sky5685610** [comment]
![image](https://user-images.githubusercontent.com/123931755/228468418-f65d05bd-bfaf-42e0-b354-52404b743c0c.png)

**Comment by sky5685610** [comment]
Done

**Comment by sky5685610** [comment]
Done

**Comment by vikasbansal2022** [comment]
Hi @sky5685610,

As discussed, Correction in RFC connection HTTP version from 1.0 to 1.1 and BLOB certificate import in STRUST recommendation fixed the issue.

Regards,
Vikas
