### ISSUE TITLE
Link Microsoft AI SDK for SAP

### ISSUE THREAD

**Issue by MartinPankraz** [microsoft/ABAP-SDK-for-Azure#138]
Our specialized OpenAI ABAP SDK offering and customers would profit from discoverability if cross-referenced here. Please add a callout to: https://github.com/microsoft/aisdkforsapabap

**Comment by vikasbansal2022** [comment]
Thank You @MartinPankraz for the suggestion. We will be adding a class to connect to Azure Open AI.

**Comment by MartinPankraz** [comment]
That is great indeed! Nevertheless increased discoverability to both projects by cross-linking would be desirable.

**Comment by vikasbansal2022** [comment]
Hi Martin, we have added our Azure Open AI Class 'ZCL_ADF_SERVICE_AZUREOPENAI.' For now, it supports Completion operation.  


![image](https://user-images.githubusercontent.com/117139514/235901123-ed7cc464-2301-4314-9329-2340c06acdc3.png)
