### ISSUE TITLE
The HTTP version specified is not supported for this operation by the server

### ISSUE THREAD

**Issue by sky5685610** [microsoft/ABAP-SDK-for-Azure#141]
hi

I try to transfer a excel file to our azure blob using GitHub SDK, I have got the token, however fail to transfer it to azure, can anyone help to check what the problem is, the error is as below:

![image](https://github.com/microsoft/ABAP-SDK-for-Azure/assets/123931755/a11b8f27-facd-469a-9723-ce942c27a10f)

**Comment by sky5685610** [comment]
Done

**Comment by vikasbansal2022** [comment]
Hi @sky5685610,

As discussed, Correction in RFC connection HTTP version from 1.0 to 1.1 and BLOB certificate import in STRUST recommendation fixed the issue.

Regards,
Vikas
