### ISSUE TITLE
Error activating objects 

### ISSUE THREAD

**Issue by egger-dev-team** [microsoft/ABAP-SDK-for-Azure#142]
Hi, I get an error after pulling from Github Repo
![image](https://github.com/microsoft/ABAP-SDK-for-Azure/assets/75246567/d0d83ae2-04ae-4fda-bbec-2f196bda2dda)

I use abapGit v1.114.0

**Comment by gregorwolf** [comment]
+1 had no issues importing the project with the current 1.124.0 version.

**Comment by larshp** [comment]
@gregorwolf, any syntax errors after import? I think there are two, https://github.com/microsoft/ABAP-SDK-for-Azure/runs/14756741123

**Comment by larshp** [comment]
the syntax error is fixed with https://github.com/microsoft/ABAP-SDK-for-Azure/pull/147

**Comment by vikasbansal2022** [comment]
Thanks @larshp  for feedback. Closing this issue.
