### ISSUE TITLE
Does the interface type AAD - Azure Active Directory use the Azure Active Directory Graph API?

### ISSUE THREAD

**Issue by gregorwolf** [microsoft/ABAP-SDK-for-Azure#15]
Unfortunately there is not yet an example on how to use the interface type AAD - Azure Active Directory. So I hope you can answer my question here via this issue. I've looked for the [Azure Active Directory API](https://www.ecosia.org/search?q=azure+active+directory+api&addon=opensearch) and the first result that I've got was [Azure Active Directory Graph API](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api). But there it is strongly recomended to use the [Microsoft Graph](https://developer.microsoft.com/en-us/graph). So what API does does the interface type AAD - Azure Active Directory use? And where can I obtain the SAS Key to use this API?

**Comment by NaveenKurmadas** [comment]
We are still working on the documentation part of the remaining services. we will update them soon.
As of now, AAD service class uses Microsoft Graph API token endpoints to get the AAD token. More functionalities are still being added and will be released in next versions.
There is no SAS key for AAD. Please maintain AAD Application Secret in that field. This secret will be used to get token using OAUTH 2.0 Client Credentials grant protocol.

I understand your confusion, so we will modify the field label from SAS key to just a Key/Secret. Thanks.
