### ISSUE TITLE
Import of object ZADF_CONFIGFG failed 

### ISSUE THREAD

**Issue by abap-weasel** [microsoft/ABAP-SDK-for-Azure#150]
Error:
Field SENSITIVE_FLAG does not exist in (active version of) table *ZADF_V_RESTDEST 
Import of object ZADF_CONFIGFG failed 

Function group refers to field SENSITIVE_FLAG via 
```
ZADF_V_RESTDEST-SENSITIVE_FLAG =
ZREST_CONFIG-SENSITIVE_FLAG .
```

https://github.com/microsoft/ABAP-SDK-for-Azure/blob/f83cc2bcf16ba777ef112d7ac1d826e79d47af63/src/zadf/zadf_config_view/zadf_configfg.fugr.lzadf_configfgf00.abap#L168C18-L168C18

Field SENSITIVE_FLAG not defined in DDIC

https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zadf_config_view/zadf_v_restdest.view.xml
https://github.com/microsoft/ABAP-SDK-for-Azure/blob/f83cc2bcf16ba777ef112d7ac1d826e79d47af63/src/zadf/zadf_config.tabl.xml

**Comment by gregorwolf** [comment]
Hello @vikasbansal2022 can you please have a look at this issue. It also blocks my import of the ABAP SDK for Azure.

**Comment by vikasbansal2022** [comment]
Hi @gregorwolf  ,

I will check this and let you know once fixed.

Regards,
Vikas

**Comment by torresbj** [comment]
Hi, 

Good day. 
I just wanted to check if this SDK would still be supported? 
The issue shared above is still existing and I would like to know if this is an SDK that customers should start using or create custom ABAP codes instead. 

Thanks a lot. 

![image](https://github.com/microsoft/ABAP-SDK-for-Azure/assets/12954079/337d3a05-c3f2-4faf-9438-5694cf71e499)

**Comment by MartinPankraz** [comment]
Hey @torresbj,

This SDK is supported by the community :-) so, we appreciate any PRs or Issues to progress with it.

Its purpose is to accelerate the journey to consume Microsoft services from ABAP. You can always choose to adopt only parts of it if you wish.

For this particular item we are working to release the fix soon.

KR
Martin

**Comment by vikasbansal2022** [comment]
Hi @torresbj ,

Thanks for highlighting this. I merged another pull request pertaining to package 'ZADF_CONFIG_VIEW'. Can you please check and share your feedback if you are still facing this issue.

Regards,
Vikas

**Comment by torresbj** [comment]
> Hey @torresbj,
> 
> This SDK is supported by the community :-) so, we appreciate any PRs or Issues to progress with it.
> 
> Its purpose is to accelerate the journey to consume Microsoft services from ABAP. You can always choose to adopt only parts of it if you wish.
> 
> For this particular item we are working to release the fix soon.
> 
> KR Martin

@MartinPankraz @vikasbansal2022 

Thanks! Good to hear that it's still actively supported by the community particularly for folks like me that is still in the early stages of adoption. I will be testing vikas' fix on this issue

**Comment by MartinPankraz** [comment]
@torresbj did you manage to re-test?

**Comment by torresbj** [comment]
It did activate this time around but need to test if it's working

**Comment by vikasbansal2022** [comment]
Since Pull request us activated so closing the issue.
