### ISSUE TITLE
Object Type SUCU not supported, serialize - error

### ISSUE THREAD

**Issue by bdelangh** [Microsoft/ABAP-SDK-for-Azure#16]
Hello,

I'm using ABAPGit to pull the ABAP-SDK-for-Azure into my system.
When executing the pull, I get the following error : "Object Type SUCU not supported, serialize".

I noticed a strange file in named 'zres                          s_tabu_dis.sucu.xml'. Maybe this is the cause of the error?

Greetings,
Bart

**Comment by krdash** [comment]
Hello Bart,
We are looking into the issue and will provide you updates soon.
Thanks,
Krishna

**Comment by larshp** [comment]
See https://docs.abapgit.org/ref-supported.html

https://github.com/larshp/abapGit-Plugins is required to install the SUCU

**Comment by NaveenKurmadas** [comment]
Hello Bart  (@bdelangh ),

Can you please try again after installing the AbaptGit Plugins in your system. Thanks.

Regards,
Naveen

**Comment by larshp** [comment]
Plan is to support SUCU without the plugins, follow https://github.com/larshp/abapGit/issues/1434

**Comment by bdelangh** [comment]
Hello,
I used ABAPGit to install the plugins from https://github.com/larshp/abapGit-Plugins.
The pluginn class ZIF_ABAPGITP relies on ZIF_abapgit_definitions, which is defined as a local interface in the zabapgit program, so this results in a syntax error/dump.

Should the zabapgit program be changed to add these pluginn classes&interfaces locally or is there another version of the zabapgit program which I can use?

**Comment by krdash** [comment]
Hello Bart,
We didn't face this issue while installing these plug ins in our internal system. As this issue belongs to ABAPGit plug ins. I would request you to check with @larshp for inputs.

Thanks,
Krishna

**Comment by larshp** [comment]
@bdelangh use abapGit to install https://github.com/larshp/abapGit then you will get all the individual objects instead of the "compiled" report

**Comment by hobru** [comment]
Hello @larshp , 
I am facing the same issue. I tried to install both abapGit and the abapGit-Pluings via abapGit (well of course I could only install abapGit via abapGit after installing it manually...) but I am still getting the SUCU error message. 
@krdash Is this an issue with our ABAP-SDK-for-Azure repository?

Thanks, 
 Holger.

**Comment by larshp** [comment]
okay, thanks, I wont have access to my test systems until Friday. But I've posted in Slack if somebody can help/test

**Comment by bigld** [comment]
For me SUCU error only appears w/o abapGit-Plugins
After installation of abapGit and abapGit-Plugins installation of ABAP-SDK-for-Azure works fine.

@hobru: whats the length of report ZABAPGIT in your system?

**Comment by hobru** [comment]
Now it works!!!
At first I had installed it using Copy & Paste from GitHub. After that I used it to install the abapGit-Plugins (which did not yet help) and to clone the abapGit repo (my ZABAPGIT has now 71 lines) itself (which for me also didn't work yet). 
The issue most likely was, that I never restarted abapGit after installing the new version of abapGit or abapGit-Plugins. Now, that I tried again (I didn't do anything else) it works. 

THANK YOU for your support.

**Comment by larshp** [comment]
sometime in the future SUCU will be supported natively, hope soon 😄 just need time

**Comment by krdash** [comment]
Thank you all for your support .

Hi Holger,
We don't see any issue in our internal system for ABAP SDK for Azure .
Thanks,
Krishna

Hello Bart ,  @bdelangh - please can you try again in your system and let us know if its working. Thanks, Krishna

**Comment by bdelangh** [comment]
Hi Krishna, Lars,

I used the 'compiled' ABAPGit to install the ABAPGit 'Development Edition' ( https://github.com/larshp/abapGit) as per comment of Lars.  Then I used the ABAPGit 'Development Edition' to install the ABAPGit Plugins ( https://github.com/larshp/abapGit-Plugins). 
Afterwards the Azure SDK installed successfully.
I'll close the issue.

Many thanks for your support!

Greetings,
Bart

**Comment by gregorwolf** [comment]
Dear @bdelangh ,

I would suggest that you update the Installation section of the Guide [ABAP SDK for Azure – Github](https://github.com/Microsoft/ABAP-SDK-for-Azure/blob/master/ABAP%20SDK%20for%20Azure%20-%20Github.pdf) to mention this additional requirement. Maybe you can convert the guide also into something that can be edited easier to allow pull requests.

Best regars
Gregor

**Comment by krdash** [comment]
@gregorwolf - Hello Gregor, Thank you for the suggestion. 
We are working on ABAP SDK for Azure - GitHub document to mention the abapGit-Plugins as a pre-requisite for installing ABAP SDK for Azure and we have plans to convert all the guides to md file format as well.
We would keep you posted on this soon. Thanks, Krishna
