### ISSUE TITLE
Azure Key Vault permission in ABAP SDK Implementation guide for Azure Active Directory

### ISSUE THREAD

**Issue by gregorwolf** [Microsoft/ABAP-SDK-for-Azure#19]
Hello ABAP SDK for Azure Team,

I'm currently following the "ABAP SDK Implementation guide for Azure Active Directory". It might be worth mentioning that the Azure Key Vault permission can only be found after a "Key vault" was created in the corresponding service.

Best regards
Gregor

**Comment by krdash** [comment]
@gregorwolf - Hello Gregor,
Thank you for the note . we are looking into the document and keep you updated on this.
Thanks and regards,
Krishna

**Comment by krdash** [comment]
@gregorwolf - Hello Gregor, 
As ssuggested, we updated ABAP SDK implementation guide for Azure Active Directory. Thank you for your valuable feedback.
