### ISSUE TITLE
Path Prefix in Step "Creation of RFC destination to Azure Active Directory" of the Implementation Guide for Azure Active Directory

### ISSUE THREAD

**Issue by gregorwolf** [Microsoft/ABAP-SDK-for-Azure#21]
Hello,

it should be mentioned in the Implementation Guide for Azure Active Directory that the part:

72f988bf-86f1-41af-91ab-2d7cd011db47

of the Path Prefix in Step "Creation of RFC destination to Azure Active Directory" should be replaced by the users Directory ID. I've found that in the Properties Section of the AAD Service.

Best regards
Gregor

**Comment by krdash** [comment]
@gregorwolf - Hello Gregor,
we updated ABAP SDK implementation guide for Azure Active Directory with new Tenant ID creation link as per your note. Thank you for your valuable feedback.
