### ISSUE TITLE
Updating objects to latest abapGit format

### ISSUE THREAD

**Issue by larshp** [Microsoft/ABAP-SDK-for-Azure#26]
Hi,
I get a lot of diffs, some of these are caused by abapGit being updatated with new logic.

E.g. ENQU logic as updated at end of August, https://github.com/larshp/abapGit/pull/1883

Suggest you update to latest abapGit(after merging PRs) and update objects

![image](https://user-images.githubusercontent.com/5888506/48851817-42763100-edac-11e8-9a0b-cdd2b2c5dc48.png)

**Comment by NaveenKurmadas** [comment]
Hi @larshp,
I updated to latest abapgit and now getting dump.
Similar to issue [https://github.com/larshp/abapGit/issues/1919]

![image](https://user-images.githubusercontent.com/35898274/48898605-2ab5b000-ee73-11e8-87f3-0354f9732212.png)

Regards,
Naveen

**Comment by larshp** [comment]
try "updating manually the class ZCL_ABAPGIT_BACKGROUND" as mentioned in the issue

I recommend keeping the full report in eg. program ZABAPGIT_FULL in $TMP, that way it is easier to find the differences in case the automatic update fails

**Comment by krdash** [comment]
Hello Lars @larshp @Microsoft/abapsdk  - Updated the objects after latest abapgit . Thank you for your valuable feedback. Regards, Krishna

**Comment by larshp** [comment]
cool, closing 👍
