### ISSUE TITLE
Diff TABL ZREST_MONITOR

### ISSUE THREAD

**Issue by larshp** [Microsoft/ABAP-SDK-for-Azure#27]
Get following diff after installing, update file to latest abapGit format, see https://github.com/larshp/abapGit/issues/1722

![image](https://user-images.githubusercontent.com/5888506/48966941-ad587f80-efd9-11e8-8eae-8030d6b3cd9f.png)

**Comment by krdash** [comment]
@larshp - Hello Lars, merged the update to master branch. Thanks, Krishna

**Comment by larshp** [comment]
one small step at a time 😄
