### ISSUE TITLE
link to blog

### ISSUE THREAD

**Issue by larshp** [Microsoft/ABAP-SDK-for-Azure#3]
Hi,
Suggest adding a link to https://www.microsoft.com/itshowcase/Article/Content/1040/Streamlining-business-processes-with-SAP-connectors-and-Azure-services

As it gives the background for the code in the repo

**Comment by NaveenKurmadas** [comment]
Thanks for the suggestion. We are working on a refined documentation. We will upload in next couple of days. Thanks.

**Comment by NaveenKurmadas** [comment]
We have uploaded the enhanced documents. Closing this issue.
