### ISSUE TITLE
Package Z_AZURE_ABAPSDK contains dev. objects and therefore cannot be a main package

### ISSUE THREAD

**Issue by matt1as** [Microsoft/ABAP-SDK-for-Azure#33]
I'm trying to install ABAP-SDK-for-Azure, but keep running into this problem. I have checked that Z_AZURE_ABAPSDK is not a main package, so I don't know where this is coming from.

I've followed the guide ABAP SDK for Azure - Github.pdf but still get the below error.

```
Package Z_AZURE_ABAPSDK contains dev. objects and therefore cannot be a main package

Message no. PAK019

Diagnosis

The package Z_AZURE_ABAPSDK contains development objects (except subpackages and package interfaces) and therefore cannot be a main package.

Main packages can only contain subpackages and package interfaces as development objects.

```

**Comment by matt1as** [comment]
I had the graph-support fork installed, and that places tables directly under the main package. I moved them into another package and now it's working

**Comment by krdash** [comment]
Hello @matt1as - Mattias Thank you for letting us know the issue. Presently Graph API related code changes haven't been merged to the master branch and we will be merging the changes in master branch soon and as you correctly mentioned that there are some objects which are present in main package  Z_AZURE_ABAPSDK and we need help from Gregor to transfer these objects from this package and put it in sub packages.
Hello @gregorwolf  Gregor- request your help on this. Thanks, Krishna

**Comment by gregorwolf** [comment]
I've moved the files into the correct subfolder.

**Comment by krdash** [comment]
Thank you @gregorwolf for your quick help on this. We have pushed these new changes to our staging branch and we will be merging the same to master branch after checking the conflicts in the code with master branch and some smoke testing. Thanks, Krishna
