### ISSUE TITLE
Documentation for Service Bus integration

### ISSUE THREAD

**Issue by chasselb** [microsoft/ABAP-SDK-for-Azure#36]
Hi,

in the documentation it states that other types of Azure services are coming soon. I got a spec to integrate a service bus, is there any documentation available for it?

thanks and regards,
Cris

**Comment by krdash** [comment]
Hi @chasselb Cris, 
Thank you for reaching out to us regarding your query. Presently  ABAP SDK library supports Service Bus.
and you can try to use  class 'ZCL_ADF_SERVICE_SERVICEBUS' similar to 'Azure Event hub' service . 
Also,we have working demo program for this and we would keep you posted with the required steps for integrating to Azure Service Bus topics as soon as possible. Meanwhile we would like you to go through the below links for getting more information on creating service bus namespace and Topics in Microsoft Azure portal.
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-create-namespace-portal
 Thanks, Krishna

**Comment by krdash** [comment]
Hi @chasselb Cris @Microsoft/abapsdk ,
We had committed a sample program ZADF_DEMO_AZURE_SERVICEBUS for Azure service bus inside package 'ZADF_DEMO' for your reference. Please go through the comments section to understand the overview of pre-requisite steps of configuration before executing this program. We are also in the process of creating an implementation guide on Service bus usage similar to Eventhub and it would take some time. Request you to execute the program and let us know in case of any issues. Thanks, Krishna

**Comment by gregorwolf** [comment]
Hi @chasselb can this issue be closed?
