### ISSUE TITLE
Incorrect SAS key for Service bus integration scenario

### ISSUE THREAD

**Issue by smithesht** [Microsoft/ABAP-SDK-for-Azure#38]
Method GET_SAS_TOKEN in class ZCL_ADF_SERVICE_SERVICEBUS is evaluating incorrect SAS key service bus integration scenarios. Specifically, the value for "skn" entity is incorrect. Screenshots of before and after scenario have been attached.
[Document1.pdf](https://github.com/Microsoft/ABAP-SDK-for-Azure/files/3055223/Document1.pdf)

**Comment by krdash** [comment]
Hello @smithesht - Thank you for letting us know the issue. Now issue has been fixed and changes have been committed in master branch. Please share your feedback. Thanks,Krishna

**Comment by smithesht** [comment]
The issue is now fixed. Thanks!
