### ISSUE TITLE
Append BLOB

### ISSUE THREAD

**Issue by VivekanandaRao** [microsoft/ABAP-SDK-for-Azure#39]
Is there a demo/sample where the AppendBlob mode is working?
I tried the ZADF_DEMO_AZURE_BLOB program which works fine in BlockBlob mode and able to update the file.
When I change BlobType to AppendBlob ('A'), I can see the file created in the Container, however no data written to file. Keep getting the response code "500 Network connection broken"
Below are the steps I am following:-
1. Calling factory method to instantiate Blob Storage Client (ZCL_ADF_SERVICE_FACTORY=>CREATE)
2. Setting Expiry time (ZCL_ADF_SERVICE_FACTORY->ADD_EXPIRY_TIME)
3. Forming String-to-sign for SAS token generation (ZCL_ADF_SERVICE_BLOB->STRING_TO_SIGN)
4. Create Blob for Blob Storage (ZCL_ADF_SERVICE_BLOB->CREATE_APPEND_BLOB)
5. Sending Converted SAP business data to BLOB Storage in Azure (ZCL_ADF_SERVICE_FACTORY=>SEND)

Thanks in advance.

**Comment by krdash** [comment]
@VivekanandaRao @microsoft/abapsdk - Hello Vivekananda, Thank you for reaching out to us on the issue. we are looking into it and provide you updates as soon as possible. Thanks, Krishna

**Comment by krdash** [comment]
@microsoft/abapsdk @VivekanandaRao - Hello Vivekananda, We have replicated your issue with http status '500' in our staging environment.  Please follow below steps for the resolution and we are also in the process of doing code changes to pass content-length value dynamically based on the data packet size from the calling program and will commit the same along with new features of Blob.

Inside method of ZCL_ADF_SERVICE_FACTORY=>SEND for blob service class, header with attribute 'Content-Length' having value '1048' is being used in the current version of code which is causing issue for internal server error ( http status 500) . Can you provide smaller size for content length like e.g '10' and execute your program. It should resolve your issue.
This attribute 'Content-Length' is a mandatory attribute whose value should be dynamic based on the data size ( in Bytes ) by dividing your complete data into no. of chunks.

add_request_header( iv_name = 'Content-Length' iv_value = '1048' ).

For additional information on Append block functionality, Please go through below doc link and let us know in case you would like us to share any other information.
https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob
https://docs.microsoft.com/en-us/rest/api/storageservices/append-block

Thanks,
Krishna

**Comment by gregorwolf** [comment]
Hi @VivekanandaRao can this issue be closed?

**Comment by PramishaLadha** [comment]
Hello Vivekananda,
Hope your query is addressed. Please contact us in case of more queries/issues/support.

We will be closing this issue.
thank you.

Best regards,
Pramisha
