### ISSUE TITLE
Improvements for IMPLEMENTATION GUIDE ON ABAP SDK FOR AZURE V1.0

### ISSUE THREAD

**Issue by gregorwolf** [Microsoft/ABAP-SDK-for-Azure#4]
I've worked through the implementation guide and got the connection to EventHub working. But I would suggest the following corrections and suggestions:

- Suggestion: Please provide the guide as a md file. That would allow easier improvements by sending a pull request
- Suggestion: Provide links to the general documentation of the service that is accessed to provide more context
- Correction: 4.1 Remote function call Destination Creation
The sample Target Host is testhub.servicesbus.windows.net. The correct domain is .servicebus.windows.net. I would suggest that the documentation uses &lt;Your-namespace>.servicebus.windows.net.
Only after I've removed the Path Prefix from the SM59 destination the send of messages worked. So either this topic in the documentation needs to be adjusted or the path had to be left out in the sample report
- Correction: 4.3 Usage of ABAP SDK for Azure EventHub
The constant gc_interface is set to value 'DEMO_EHUB'. But for the configuration DEMO_HUB is used.
- Suggestion: Provide also an example how the sent message can be read. I've used the [node.js example](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-nodejs-how-to-use-queues):
```
var azure = require('azure');
var serviceBusService = azure.createServiceBusService();

var queueName = 'test123';

serviceBusService.receiveQueueMessage(queueName, function(error, receivedMessage){
    if(!error){
        console.log("Message received and deleted");
        console.log(receivedMessage);
    } else {
        console.log("Error: ");
        console.log(error);        
    }
});
```

**Comment by NaveenKurmadas** [comment]
Thanks for the feedback. We are creating a new enhanced Installation and Implementation guide with lot more details and Demo programs. We will make sure to incorporate your feedback as well in it.

**Comment by NaveenKurmadas** [comment]
We have enhanced the documents. Please check and let us your feedback.
