### ISSUE TITLE
Accessing SAP OData service from Azure app service C# project

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/ABAP-SDK-for-Azure#40]
Hello Team,

I am working on the implementation of Chatbot using the Microsoft Azure Bot service. We created the Chatbot and implemented the bot framework C# project. Also deployed the same in Azure app service. Now we need to get data from SAP using our Chatbot (like invoice status, Shipper status etc), where if user asks for that to the chatbot, it will ask for the relevant inputs from user and using that the bot will call the implemented OData REST service in SAP for getting the status.
Our organization wants the Chatbot to execute the OData service in SAP with the user ID of the user who is currently requesting for the status in Chatbot instead of a generic dedicated SAP user ID to call from C# end. This is to avoid SAP license issues and also to enhance the security on the usage of Chatbot with SAP system. Is there any way where we can get the token for that particular user using that we can call the OData service in SAP?
I saw the AAD authentication for sending data from SAP to Azure based applications using Azure SDK for ABAP, but this is the other way around, where we need to get the token (for that user) in azure that will be accepted by SAP for executing that OData services. Thanks in advance for your reply.

Regards,
Vignesh.

**Comment by krdash** [comment]
@Vigneshramkumar  @microsoft/abapsdk  - Hello Vignesh, Thanks for reaching out to us for your query.
ABAP SDK for azure includes AAD service class which would help ABAP developer to get token from Azure active directory for authentication with  Azure resources. Regarding your query on retrieving token  in .NET environment for the generic user for accessing SAP Odata servcies, please try to go through below links and refer section of 'configure SAP NetWeaver for OAuth' for a service user.

<https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sap-netweaver-tutorial> 

Please can you post your query/issue in below link to get more information.

https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory/saas-apps/sap-netweaver-tutorial.md

Hope the above information would help for your scenario.

Thanks,
Krishna

**Comment by hf-kklein** [comment]
Hey @Vigneshramkumar . I'm not sure if this ABAP SDK for Azure is exactly what you're looking for.  I'd suggest you to read about Core Data Services (CDS). With CDS you can define kind of a SQL view and expose it to the outside world using an OData interface, that is automatically generated.. The `@AccessControl` annotations in the CDS definition allows you to restrict the access to data from your SAP system using existing SAP standard authoritiy check objects (known from transaction `pfcg` and alike). The user specific access rights can be managed with SAP Principal Propagation. All of these components aren't documented very well and definitily do have bugs. But it works.

**Comment by gregorwolf** [comment]
Hi @Vigneshramkumar I think that issue should be closed as it is not related to the Azure SDK for ABAP.

**Comment by krdash** [comment]
Thanks Gregor @gregorwolf for your suggestion. 
Hi @Vigneshramkumar - Presently we are closing this issue and please let us know in case you see any issues related to Azure SDK for ABAP . Thanks, Krishna Chandra Dash
