### ISSUE TITLE
Object name conflict with Customer Objects

### ISSUE THREAD

**Issue by jools-chin** [microsoft/ABAP-SDK-for-Azure#41]
Hello,

I'm trying to import this into our Dev environment and there are objects in there that have naming conflicts with existing objects our system. This is the Data Element ZPSTATUS and Domain ZPSTATUS. In our system, we already have ZPSTATUS created for holding print statuses. 

Any possibility of renaming these to something more unique to the SDK which will not potentially affect existing objects?

Thanks in advance.

**Comment by larshp** [comment]
also see https://github.com/microsoft/ABAP-SDK-for-Azure/issues/8

**Comment by atarigui** [comment]
and same comment as in the namespace issue.
it requires a proper namespace (not customer namespace obviously).
Proposal: /AZURE/

**Comment by vikasbansal2022** [comment]
Thanks @jools-chin for the feedback,

We are working towards unified namespace for the next release will keep you posted.

Regards,
Vikas
