### ISSUE TITLE
Primary Key for EventHub connection in table ZADF_CONFIG cannot be updated using sm30

### ISSUE THREAD

**Issue by hf-kklein** [microsoft/ABAP-SDK-for-Azure#45]
The EventHub documentation says:
> Every time you generate a new SAS key in portal, you need to change in this config
table.

But when I'm trying to update the SAS key stored in table `ZADF_CONFIG` using transaction `sm30` the input field turns red, no matter what value I entered.
![grafik](https://user-images.githubusercontent.com/23094997/68291232-b7a84800-0089-11ea-8043-6edff663c98a.png)

Seems like you cannot update the secret directly. A **workaround** is to delete the entry, save and exit and then create a new entry with the same key as the old one. The disadvantage is that this requires manually re-entering other connection properties, too (like interface type, asynchronous/synchronous, retry true/false).

**Comment by krdash** [comment]
Hello @hf-kklein - Thanks for reaching out to us on your query . As per current version of SDK feature ,  ZADF_CONFIG table won't allow to update secret . As you rightly mentioned, we need to delete and create a new entry for the same and this validation is also in place to get the appropriate error message to user.
However other connection properties can be updated except SAS Key field value in table ZADF_CONFIG without any error. We will be incorporating your feedback in our future versions of release. Thanks, Krishna

**Comment by Sanjukum19** [comment]
Hi @hf-kklein,

Please note that we have incorporated your feedback and now you would be able to update the SAS key in ZADF_CONFIG table in SM30 without deleting the existing entry and creating.
Request you to pull the latest codebase for the same and let us know in case of any concerns.

Thanks,
Sanju

**Comment by Sanjukum19** [comment]
Hi @hf-kklein,

We are closing this issue. Request you to please incorporate these latest changes & let us know in case of any concerns.

Thanks,
Sanju
