### ISSUE TITLE
ZREST_UTIL has Corelation ID always set as 0 for servicebus POST

### ISSUE THREAD

**Issue by smithesht** [microsoft/ABAP-SDK-for-Azure#46]
Transaction ZREST_UTIL has Corelation ID always set as 0 for service bus POST scenario and there is always only one entry in ZREST_UTIL as a result of this. I did some debugging and figured that the problem is in method SET_GUID of class ZCL_REST_FRAMEWORK. The return parament "GUID" never gets populated with any value within the method SET_GUID but the calling program of the method is expecting a value to be returned and the returned value is being used for further processing which happens to be null in this scenario.

**Comment by krdash** [comment]
Hello @smithesht - Thanks for reaching out to us on your query. Please could you check what value is maintained in 'REPROCESS' field  of Table 'ZADF_CONFIG'. It should be left blank and this field is reserved for future versions use. Thanks, Krishna

**Comment by smithesht** [comment]
Yes, I changed the 'REPROCESS' field as blank in table 'ZADF_CONFIG' and did not fix the issue. Looks like the resolution is to make 'REPROCCESS' table field blank and also make a minor change to the method SET_GUID of class ZCL_REST_FRAMEWORK by populating value into return parameter 'GUID'. I have made this change in my instance of code and seems to have fixed the issue.
![image](https://user-images.githubusercontent.com/33437367/68598937-4f7cac00-0465-11ea-9fe9-7f46da1e6897.png)

**Comment by krdash** [comment]
Thanks @smithab - Smitha for sharing the correction and feedback. Please could you share a pull request for the commit. We are also in the process of testing the same in our staging environment as it seems there is some difference in version of the code in master branch with our staging environment. Thanks, Krishna

**Comment by smithesht** [comment]
I am not sure how to share a pull request. I use the offline version of ABAPGit.

**Comment by larshp** [comment]
hi, depending on the size of your change, you can either do the changes online, https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

or use abapGit to download the package as zip, extract the zip, and use a normal git client from there
