### ISSUE TITLE
Retry function using ZREST_UTIL has issues.

### ISSUE THREAD

**Issue by smithesht** [microsoft/ABAP-SDK-for-Azure#47]
Retry function using ZREST_UTIL has issues.
1. Irrelevant message while executing retry function. Changed the code in the local version which fixed the issue. 
![image](https://user-images.githubusercontent.com/33437367/68621195-bc5b6a80-0494-11ea-8fd6-7274130c0fc1.png)
2. An invalid token is being generated for the retry scenario. Changed the code in the local version which fixed the issue. 
![image](https://user-images.githubusercontent.com/33437367/68621329-13f9d600-0495-11ea-80d3-a17f808a69ec.png)

**Comment by krdash** [comment]
Hello @smithesht - Thanks for sharing the feedback and the correction. 
We are in the process of developing a class to handle retry functionality of Services corresponding to interface IDs maintained in ZADF_CONFIG table and will be commiting the changes and keep you posted on this. 
Thanks, Krishna

**Comment by vikasbansal2022** [comment]
Hello @smithesht - We updated the master version and re-try functionality is upgraded. Please check and let us know.

Regards,
Vikas
