### ISSUE TITLE
Does the Active Directory implementation of this SDK support Azure AD B2C?

### ISSUE THREAD

**Issue by gregorwolf** [microsoft/ABAP-SDK-for-Azure#5]
In a customer project I need to implement the management (Creation, Group assignment, Update, Deletion) of Azure AD B2C Users from an ABAP system. I've started my own implementation based on the documentation at [Azure AD B2C: Use the Azure AD Graph API](https://docs.microsoft.com/en-gb/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet). It would be great to know if the Active Directory implementation in this SDK also supports Azure AD B2C.

**Comment by NaveenKurmadas** [comment]
Current Version of ABAP SDK doesn't support this feature. We will work on this feature in next versions. If you already have developed, you can contribute to this SDK.

**Comment by gregorwolf** [comment]
With #22 a basic support for Graph is added.
