### ISSUE TITLE
Error in zcl_adf_service_keyvault after merge

### ISSUE THREAD

**Issue by larshp** [microsoft/ABAP-SDK-for-Azure#55]
Contains artifacts after git merge conflict,

https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zcl_adf_service_keyvault.clas.abap#L222

**Comment by krdash** [comment]
Thanks Lars @larshp . Corrected the lines of code in service class of Keyvault as you mentioned. 
Please could you check if it resolves the issue.

**Comment by larshp** [comment]
👍 
I've not run the code, but now it looks like it does not contain syntax errors, closing

**Comment by krdash** [comment]
Thanks for the feedback. we are also working on doing code sync up into master branch for additional features after our recent merge from 'open_source_dev' branch. We would keep you posted on this. Regards, Krishna
