### ISSUE TITLE
double up for class zcl_adf_service_graph

### ISSUE THREAD

**Issue by larshp** [microsoft/ABAP-SDK-for-Azure#57]
Hi,
The class with name "zcl_adf_service_graph" currently exists twice in the repo,

https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zcl_adf_service_graph.clas.abap

https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zadf_graph/zcl_adf_service_graph.clas.abap

found via https://travis-ci.org/dotabap/dotabap-list/builds/641600521, I run duplicate filename checks across the entire http://dotabap.org ecosystem daily.
Currently not part of the CI check, but will be implemented in https://github.com/abaplint/abaplint/issues/729

**Comment by krdash** [comment]
Thanks Lars @larshp . Correction has been done and merged into master branch. Regards, Krishna

**Comment by larshp** [comment]
thanks, closing
