### ISSUE TITLE
Use markdown for documents

### ISSUE THREAD

**Issue by zhaoshengjun** [Microsoft/ABAP-SDK-for-Azure#6]
This is a suggestion.

Use .doc/.docx/.pdf format for documents has a disadvantage: it cannot show diff. So over time, people cannot see the change history. 

The suggestion is to use markdown for all the documents.

If it's OK, I can submit a PR.

**Comment by larshp** [comment]
Also suggested in https://github.com/Microsoft/ABAP-SDK-for-Azure/issues/4

**Comment by zhaoshengjun** [comment]
@larshp You are right! I didn't see it. 

So this can be closed.

**Comment by krdash** [comment]
Thank you for your feedback. we are in the process of enhancing the documents as suggested in #4. Hence closing this issue.
