### ISSUE TITLE
double zcx_adf_service_graph

### ISSUE THREAD

**Issue by larshp** [microsoft/ABAP-SDK-for-Azure#60]
https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zcx_adf_service_graph.clas.abap

and

https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zadf_graph/zcx_adf_service_graph.clas.abap

**Comment by krdash** [comment]
Thanks Lars @larshp . Correction has been done. Regards, Krishna
