### ISSUE TITLE
Final token concatenation not correct

### ISSUE THREAD

**Issue by WebworkApp** [microsoft/ABAP-SDK-for-Azure#63]
Hello,

Final token concatenation is not correct in class zcl_rest_utility_class line 904.

The sig parameter is repeated and sr is missing: 
CONCATENATE 'SharedAccessSignature **sig**=' lv_encoded_base_address  '&**sig**=' lv_sign '&se=' lv_new_expiry_adf '&skn='wa_policy-policy INTO lv_final_token.

Should be corrected for:
CONCATENATE 'SharedAccessSignature **sr**=' lv_encoded_base_address  '&**sig**=' lv_sign '&se=' lv_new_expiry_adf '&skn='wa_policy-policy INTO lv_final_token.

Thanks for this framework, it save my day.
Nuno Morais

**Comment by krdash** [comment]
Thanks @WebworkApp  - Nuno Morais for your feedback. Now code correction has been done to include signature string for Azure servicebus along with Azure eventhub. 
we are also working on the modularization of reprocessing functionality. we would keep you posted on this soon.  For open source contribution, please refer the installation guide of abapGit.
https://github.com/larshp/abapGit
Thanks, Krishna

**Comment by krdash** [comment]
Closing the issue as correction has been merged into master branch. Please let us know in case you see any issues.
Thanks, Krishna
