### ISSUE TITLE
Issues during pulling from git

### ISSUE THREAD

**Issue by flow23** [microsoft/ABAP-SDK-for-Azure#64]
Hi,
there are several errors pulling the latest source from this git.

> Error while parsing XML file zadf_demo_azure_graph.prog.xml
> Import of object ZADF_DEMO_AZURE_GRAPH failed
> Object type SUCU not supported, serialize
> Import of object ZSDK S_TABU_DIS failed

Best regards,
Florian

**Comment by larshp** [comment]
the file is not valid xml, https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf_demo/zadf_demo_azure_graph.prog.xml

will be added in abaplint sometime, https://github.com/abaplint/abaplint/issues/667

**Comment by flow23** [comment]
Hi,

what about the second problem with the not supported object type?

Best regards,
Florian

**Comment by larshp** [comment]
second problem is related to https://github.com/microsoft/ABAP-SDK-for-Azure/issues/30

solution: install https://github.com/larshp/abapGit-Plugins

**Comment by krdash** [comment]
Hello Florian @flow23 - Please could you let us know if this issue has been resolved? Thanks, Krishna

**Comment by flow23** [comment]
Hi @krdash, @larshp,
still the same problem.
I installed the abapGit-PLugins and then I did a fresh pull from this repo.
Same issue:
`Object type SUCU not supported, serialize
Import of object ZSDK S_TABU_DIS failed`

**Comment by larshp** [comment]
still suggest to use the native format, see comment in https://github.com/microsoft/ABAP-SDK-for-Azure/issues/30

**Comment by krdash** [comment]
Thanks Lars @larshp for your suggestion and help .
Hello Florian @flow23 , 
Please could you try steps as mentioned in #30 and let us know it resolves the issue.
Thanks,
Krishna

**Comment by flow23** [comment]
I solved it.
I did the following:

1. Install abapGit via abapGit
2. New pull from this the repository 

Best regards,
Florian
