### ISSUE TITLE
Syntax error / Issue when activating the class ZCL_ADF_SERVICE_DEFAULT_CONFIG

### ISSUE THREAD

**Issue by netweaver-abap-sdk-user1** [microsoft/ABAP-SDK-for-Azure#66]
Hi,

We just recently pulled the ABAP-SDK-for-Azure repository and are trying to activate the objects.  However, we are activating the class ZCL_ADF_SERVICE_DEFAULT_CONFIG, we got the following error below:

Class ZCL_ADF_SERVICE_DEFAULT_CONFIG,Method CONSTRUCTOR
Field "VALUE" is unknown. It is neither in one of the specified tables
nor defined by a "DATA" statement. "DATA" statement.

Do you know what might have caused this?

Thanks

**Comment by christianguenter2** [comment]
I guess your netweaver version is below 7.40? Thus not supported.

**Comment by netweaver-abap-sdk-user1** [comment]
Thanks.  Yes our version is 7.31.  Since it's not supported, I'll try to port the codes to adapt to 7.31.  It might take long but let us see.  By chance was there any reason why the codes were not or didn't use 7.31 as the base (is it just a timing issue … that is, 7.40 was the common NetWeaver version at the time of the first release of the SDK?).

**Comment by krdash** [comment]
Hi @netweaver-abap-sdk-user1 -  Thanks for the feedback. We are looking into the issue and keep you posted on its resolution as initial version of SDK was based on 7.31. Meanwhile please could you try to fix this syntax error and commit the changes. Regards, Krishna

**Comment by PRREDDYC** [comment]
Hello @netweaver-abap-sdk-user1  - We have commited  changes related to the class ZCL_ADF_SERVICE_DEFAULT_CONFIG and Interface ZIF_ADF_AZURE_DEFCONFIG  to make it compatible with version 7.3 . Closing the issue now , could you please reopen if the issue persists.

Thanks,
Praveen Kumar Reddy Chinta
