### ISSUE TITLE
Deletion of logs (table ZREST_MO_PAYLOAD is growing very fast)

### ISSUE THREAD

**Issue by netweaver-abap-sdk-user1** [microsoft/ABAP-SDK-for-Azure#68]
Hi,

Is there a clean-up job / program created for this table? How do we maintain this table (that is, from transaction ZREST_UTIL, we see that that the log selected is being marked as deleted.  However, we cannot do multiple selection of rows)?

Thanks,
Allaine

**Comment by krdash** [comment]
Hello Allaine @netweaver-abap-sdk-user1 @microsoft/abapsdk 
Thanks for reaching out to us on your query.
Yes, we have a clean up job for ZREST_UTIL log tables like ZREST_MO_PAYLOAD and It has been missed out from ZREST package.
we are working on this to commit the program as soon as possible. Thanks for your feedback.
Regards,
Krishna Chandra Dash

**Comment by PRREDDYC** [comment]
Hello Allaine @netweaver-abap-sdk-user1 @microsoft/abapsdk
You can refer below  programs which has been committed now . Please let us know in case if you see issues in executing these programs.
-  ZREST_MONITOR_ARCHIVE for marking deletion and deletion of ZREST_UTIL tables .
   ZREST_TABLES_ARCHIVE for purging ZREST related tables .

Thanks & Regards,
Praveen Kumar Reddy Chinta

**Comment by netweaver-abap-sdk-user1** [comment]
Hi,

We do not have issues on executing the program and it seems to work okay.  Thanks.
However, we would like to ask if there are any options for the log not to write to ZREST_MO_PAYLOAD table?  That is, we prefer to have the log entries but not the payload.

Thanks again,
Allaine
