### ISSUE TITLE
Getting error with ZADF_DEMO_AZURE_GRAPH

### ISSUE THREAD

**Issue by Vijisoms** [microsoft/ABAP-SDK-for-Azure#76]
Hi,

**I am using the ABAP SDK for Azure to trigger pipelines in Azure data factory as soon as there is change in SAP BW data in ADSO's**

I have downloaded the ZIP file offline to create the ABAP SDK for creating blobs from SAP BW system. The blobs are created successfully.
I am trying to transport this change to test system where I see the below syntax error in **ZADF_DEMO_AZURE_GRAPH** program.
103	Program ZADF_DEMO_AZURE_GRAPH
		Method "CREATE_USER" is unknown or PROTECTED or PRIVATE.
112	Program ZADF_DEMO_AZURE_GRAPH
		Field "LV_USER_RESPONSE" is unknown.
113	Program ZADF_DEMO_AZURE_GRAPH
		Field "LV_HTTP_STATUS" is unknown.
119	Program ZADF_DEMO_AZURE_GRAPH
		Field "LV_USER_RESPONSE" is unknown.
132	Program ZADF_DEMO_AZURE_GRAPH
		Method "GET_USERS" is unknown or PROTECTED or PRIVATE.
140	Program ZADF_DEMO_AZURE_GRAPH
		Field "LV_HTTP_STATUS" is unknown.
141	Program ZADF_DEMO_AZURE_GRAPH
		Field "LV_USER_RESPONSE" is unknown.
The **ZADF_DEMO_AZURE_BLOB** blob service program is not impacted by this error, but It gives the syntax error for the graph demo program. Could You please suggest what correction I need to do or should I have to download latest ZIP file which was committed 3 days before.
If I need to install from latest zip file, should I have to uninstall the existing ZABAPGIT or will it just just overwrite the changed objects. Please guide me the procedure to do this.
This is the first time I am using this so need your guidance.

**Enhancement to the existing ABAP SDK** -- All these enhancements are working perfectly.
Also I need to mention I have few objects created after enhancing from existing ZBAP SDK code for blob creation 
I have created a copy of ZADF_DEMO_AZURE_BLOB program and a new Z table to integrate with the current ABAP SDK objects. This Z table holds list of all the ADSO from BW for which a trigger blob is placed in ADLS Gen2. Once the blob is placed in Gen2 the subsequent data ingestion happens from SAP BW to ADLS Gens using ADF pipelines.
**Any new ADSO to be ingested in to Gen2 is added to this new Z table and the new ABAP program which is scheduled every 5 mts will take care of placing the blob file in Gen2.**

**Comment by krdash** [comment]
Hi @gregorwolf - Please could you help on this syntax issue for demo program : ZADF_DEMO_AZURE_GRAPH. Thanks, Krishna

**Comment by krdash** [comment]
Hi @Vijisoms - you can also leverage 'Online' option using ZABAPGIT for pulling latest changes of SDK from current source code repository . Please refer the installation guide to refer the clone URL and other details.
https://github.com/microsoft/ABAP-SDK-for-Azure/commit/7de07cdcf35e8ef60a292d1e6f845bfe3bc39394
Hi Lars @larshp - Please suggest us if 'offline' option of using ZIP file can also allow the pull of latest changes of SDK without recreating the objects?
Thanks,
Krishna

**Comment by gregorwolf** [comment]
Sorry @Vijisoms my last change wasn't complete and the exception class ZCX_ADF_SERVICE which I've defined as not final wasn't checked in. I've corrected that with the linked pull request. But please update your version of ZADF_DEMO_AZURE_GRAPH as I've commented the section with the user creation due to it's currently missing implementation.

Regarding your changes I suggest that if you can't use abapGit online you should get an ABAP Developer Edition running in a Virtual Machine i.e. on your private laptop, clone the project there and then start with your contribution.
