### ISSUE TITLE
Start 2FA process on an authenticated user

### ISSUE THREAD

**Issue by JoseMunozHerrera** [microsoft/ABAP-SDK-for-Azure#78]
Hello,

Do you know if there is the posibility to start the 2FA process for the user that is already logged in?

Imagine that I'm in an SAP Gui application and I have two buttons, approve & reject, if user press approve I want to raise only the 2FA for the current user, previously that user was authenticated with OAUTH 2 agains azure aad.

Thanks & regards

**Comment by vikasbansal2022** [comment]
Hi @JoseMunozHerrera  

This issue looks like 2F Authentication for SAP Gui.  Not sure I understand correctly. if you are looking for SAP connectivity for Azure services. Please let us know.

Regards,
Vikas
