### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by larshp** [microsoft/ABAP-SDK-for-Azure#8]
Hi,
The repository contains some objects with quite generic names, eg:
FUGR ZREST
TABL ZREGISTER
DOMA ZCLASSNAME
DTEL ZCHAR75
DTEL ZORIGINAL
DTEL ZURI
DTEL ZUNAME
For these, there is a theoretical chance that the customer already has an object with identical names in their system.

I recommend prefixing objects to lower the risk, eg.
FUGR Z_AZURE_REST
TABL Z_AZURE_REGISTER
DOMA Z_AZURE_CLASSNAME
DTEL Z_AZURE_CHAR75
DTEL Z_AZURE_ORIGINAL
DTEL Z_AZURE_URI
DTEL Z_AZURE_UNAME
or something similar

**Comment by krdash** [comment]
@larshp -
We are looking into your suggestion for getting a unique Namespace.
I have one query on ABAPGit to understand whether ABAPGit would show any object overwriting warnings while doing the pull or clone from the repository to SAP system. Thanks

**Comment by larshp** [comment]
unique namespace: in my opinion it is easier just to prefix

overwrite: yes it shows warnings if the objects it tries to overwrite are outside of the expected package hierarchy(main repo package)

**Comment by bigld** [comment]
@krdash So, is ZxxADFxx the actual prefix Namespace (e.g. ZCL_ADF_..., ZADF_S_STRUC...)?
Should we move ZREST to ZADF one by one?

**Comment by atarigui** [comment]
What is the status on this? It seems to me that the correct way to do it is to introduce a proper name space, instead of customer namespace Z...
For instance /AZURE/
Everything else will cause problems at some point...

**Comment by bigld** [comment]
Namespace must be Z or Y!
For reserved Namespaces like /AZURE/ one needs special key (producer/repair) to create objects in this namespace!

**Comment by larshp** [comment]
cool

one tip, you can setup abaplint to automatically check the objects have the preferred prefix, example at https://github.com/abapGit/abapGit/blob/main/abaplint.json#L335-L339
