### ISSUE TITLE
ABAP SDK For Azure installation with 750 version

### ISSUE THREAD

**Issue by IndiraSomavarapu** [microsoft/ABAP-SDK-for-Azure#89]
Hi, I tried to install ABAP SDK for AZURE for users version. after connecting to Online repo, the objects got pulled into system and see below error after all the objects were activated.
"Object type SUCU not supported, serialize import of object ZSDK S_TABU_DIS failed."

not sure of which functionality effected by not importing the above object. Could you please tell wat are the next steps to address it?

**Comment by larshp** [comment]
are you using the latest abapGit version?

**Comment by IndiraSomavarapu** [comment]
I followed the installation guide here.
https://docs.abapgit.org/guide-install.html

Install standalone version step1 - points to code for ZABAPGIT_STANDALONE - I opted this as i am not looking for developer version

**Comment by IndiraSomavarapu** [comment]
Any thoughts on how to resolve this one?

**Comment by larshp** [comment]
are you using the latest abapGit version? the version is listed in the bottom of each abapGit screen, please do a screenshot and paste it here,

**Comment by IndiraSomavarapu** [comment]
https://github.com/abapGit/abapGit
![image](https://user-images.githubusercontent.com/76130840/106012484-15ef8b00-6081-11eb-9500-0a9768d6bfd5.png)

**Comment by larshp** [comment]
okay...

does the class `zcl_abapgitp_object` exist in your system?

**Comment by IndiraSomavarapu** [comment]
No, it doesnt.

**Comment by IndiraSomavarapu** [comment]
Any suggestions here?

**Comment by larshp** [comment]
hmm, actually I get the same error,

![image](https://user-images.githubusercontent.com/5888506/106026285-ed3fb380-60c9-11eb-8f2c-84ab142fea58.png)

**Comment by IndiraSomavarapu** [comment]
Ok, Are you planning to fix that, and how long it would take?
what functionality does this affect? Should I be able to prototype in SAP to the event hub with this error in place?

**Comment by larshp** [comment]
so, @microsoft has not updated https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zsdk%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20s_tabu_dis.sucu.xml to use the native abapGit SUCU handler

as raised as issue 2 years ago, https://github.com/microsoft/ABAP-SDK-for-Azure/issues?q=is%3Aissue+SUCU+is%3Aclosed

so, try installing https://github.com/abapGit/abapGit-Plugins to the local system

**Comment by larshp** [comment]
and notice that https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zrest/zres%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20s_tabu_dis.sucu.xml was updated to use the native SUCU handler

and https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zsdk%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20s_tabu_dis.sucu.xml uses the plugin

🤷‍♂️

**Comment by IndiraSomavarapu** [comment]
Installing developer version of gitclient and abapgit handlers resolved the above issue
