### ISSUE TITLE
BADI implementation ZADF_EDIT_AUTH

### ISSUE THREAD

**Issue by larshp** [Microsoft/ABAP-SDK-for-Azure#9]
Hi,
I know the code in the implementation is commented,
https://github.com/Microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zcl_im_adf_edit_auth.clas.abap

But having the badi implementation in git, customers will install the badi implementation, https://github.com/Microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zadf_edit_auth.sxci.xml
which can be seen as modifications to the SAP standard processes.

In this case it looks like the implementation is for enforcing internal Microsoft rules. I suggest moving the implementation to a different package in the Microsoft SAP system, so you still have it internally, but not part of the git repository.

**Comment by NaveenKurmadas** [comment]
It is imported to Github by mistake. I will delete it from Github. Thanks.

**Comment by NaveenKurmadas** [comment]
We have deleted the BADI implementation from the source code.
