### ISSUE TITLE
AZURE EventGRID

### ISSUE THREAD

**Issue by IndiraSomavarapu** [microsoft/ABAP-SDK-for-Azure#90]
Is ABAP SDK for AZURE support Azure EventGRID as well?

**Comment by vikasbansal2022** [comment]
Hi @IndiraSomavarapu ,

Thanks for reaching out. We are working on this as part of our next release. Will keep you posted.

Regards,
Vikas

**Comment by vikasbansal2022** [comment]
Hi @IndiraSomavarapu 

Event Grid Integration is added to Git HUB. you can download the latest Git Hub release and use it in your landscape.

Regards,
Vikas
