### ISSUE TITLE
SUCU

### ISSUE THREAD

**Issue by larshp** [microsoft/ABAP-SDK-for-Azure#92]
see https://github.com/microsoft/ABAP-SDK-for-Azure/issues/89

Please move the other SUCU object to native abapGit

**Comment by abap-weasel** [comment]
+1     Also faced this issue.

**Comment by mithunkr** [comment]
+1
Even with the latest version of abapgit 1.109.0, I still get the error "Object type SUCU is not supported by this system".

**Comment by vikasbansal2022** [comment]
Hi @larshp : I updated the serializer in zsdk s_tabu_dis.sucu.xml file and merged with master branch. We tried to pull this file in our system, and it was success. 

Please close this issue.
