### ISSUE TITLE
OAUTH for Servicebus

### ISSUE THREAD

**Issue by 454abp** [microsoft/ABAP-SDK-for-Azure#95]
I am using the ABAP SDK for sending events to the servicebus from Azure. In our landscape we are sending each event type to a different topic. This makes it rather complex to share OAUTH keys for all different topics, morover all config and all RFC destinations need to be define for each topic.

In order to solve this i have enhanced some of the classes so that we have a dynamic topic and added basic OAUTH capabilities. Are there any plans to extend the API with such a functionality, i.e. to be able to perform OAUTH authentication to service bus instead of SAS keys?

**Comment by Sanjukum19** [comment]
Hi @454abp 

Thank you for your inputs. We have now added another capability to ABAP SDK which will allow to access Service Bus via token fetched from Azure Active Directory. Thus, supporting OAuth feature in turn via AAD registered app.
We have also modified the Service Bus Demo program with relevant steps required to set up configuration along with the required methods to fetch AAD token.

Kindly let us know if we can close this issue.

**Comment by 454abp** [comment]
Hi @Sanjukum19,

I had in the meantime in my local development already added support for the ABAP OAUTH client  and a more dynamic way to call various topics with the same configuration. Is this anything which could be of interest for a wider audience?

I will however try to pull the changes and have a look. Has the documentation been updated on how to implement the AAD authentication?

/Florian

**Comment by Sanjukum19** [comment]
Hi Florian,

Yes, it would be really great if you could share your feature as well.
As for documentation, we have not released yet. However, we have mentioned the steps to be configured along with the required methods to be called for fetching the token. Kindly refer to the demo program 'ZADF_DEMO_AZURE_SERVICEBUS' for the same and let us know in case of any concerns.

Thanks,
Sanju

**Comment by Sanjukum19** [comment]
Hi Florian,

Please note that we are closing this issue as we have added oAuth capability to Service Bus and also, we observe that you have incorporated your own feature as well to perform the same. As for dynamic capability, kindly open pull request for the same. Please let us know in case of any concerns.

Thanks,
Sanju
