### ISSUE TITLE
Auto re-process ABAP SDK

### ISSUE THREAD

**Issue by Srinivasak1984** [microsoft/ABAP-SDK-for-Azure#96]
Hi,

How to auto re-process the jobs failed in ABAP SDK to Microsoft Azure BLOB.

**Comment by vikasbansal2022** [comment]
Hello @Srinivasak198 - Thanks for reaching out We updated the SDK master version and re-process job program ZREST_SCHEDULER functionality is upgraded. Please check and let us know.

Regards,
Vika
